name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - production

jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install server dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to Render
        if: github.ref == 'refs/heads/production'
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"
